### ISSUE TITLE
Unable to capture connection errors

### ISSUE THREAD

**Issue by douglampe** [cody-greene/node-rabbitmq-client#17]
Steps to reproduce:

- Create new instance of Connection with invalid configuration (ex: invalid credentials) in try/catch block

Expected:

- Error handled in catch block

Observed:

- Exception thrown
- Process terminated

**Comment by cody-greene** [comment]
Errors are emitted as asynchronous events. Use connection.on("error", cb)

-------- Original Message --------

**Comment by douglampe** [comment]
That works. Thanks.
