### ISSUE TITLE
onShutdown (documentation clarification)

### ISSUE THREAD

**Issue by tttp** [cody-greene/node-rabbitmq-client#18]
what is the best practice to properly shutdown? (I'm consuming messages)

the aim is being able to handle SIGINT/SIGTERM and wait until the messages are processed (or possibly if the processing takes too long, to nack them and leave)

the readme contains an onShutdown function, but I didn't get how/where it's supposed to be used
```
// Clean up when you receive a shutdown signal
async function onShutdown() {
  // Waits for pending confirmations and closes the underlying Channel
  await pub.close()
  // Stop consuming. Wait for any pending message handlers to settle.
  await sub.close()
  await rabbit.close()
}```

**Comment by tttp** [comment]
so far, I've been using:

```
  ['uncaughtException', 'unhandledRejection', 'SIGINT', 'SIGTERM'].forEach(
    (evt) => process.on(evt, onShutdown)
  );

```

but not sure if it's the right way

**Comment by cody-greene** [comment]
process.on('SIGINT', cb)
process.on('SIGTERM', cb)

Is exactly what is use. You might also consider once('SIGINT', cb) so you can easily kill the application with a double signal.

Capturing "unhandledException" goes beyond the scope of this project and I'd rather not discuss it here. I'm sure there's plenty of pro/con discussion on stackoverflow and elsewhere

-------- Original Message --------
