### ISSUE TITLE
Publisher Confirms - How to use

### ISSUE THREAD

**Issue by paulohsilvavieira** [cody-greene/node-rabbitmq-client#2]
Hi! I am create a example with lib for study and practice, but i not found how to get the confirmation, i found only function `confirmSelection()`, how i get the confirmation on publisher ? I read the code and found `confirm.select-ok`, but dont found how to use this method

**Comment by cody-greene** [comment]
Refer to the official (server) documentation for more information on publisher confirms https://www.rabbitmq.com/confirms.html#publisher-confirms

> To enable confirms, a client sends the confirm.select method. Depending on whether no-wait was set or not, the broker may respond with a confirm.select-ok. Once the confirm.select method is used on a channel, it is said to be in confirm mode.

> The broker then confirms messages as it handles them by sending a basic.ack on the same channel.

You can enable publisher confirms with `await channel.confirmSelect()`. This library handles publisher confirms automatically, without the need for further user intervention. When you publish a message on a channel in confirm-mode, the `await channel.basicPublish(...)` call **will resolve only when the confirmation (basic.ack) is received**.

Full example:
```typescript
import {Connection} from 'rabbitmq-client'
const rabbit = new Connection()
async function main() {
  const ch = await rabbit.acquire()
  
  await ch.confirmSelect()
  await ch.basicPublish({routingKey: 'foo.bar'}, 'some-example-data')
  await ch.basicPublish({routingKey: 'foo.bar'}, 'some-other-data')
  
  await ch.close()
  await rabbit.close()
}
main()
```


Throughout this library I have tried to document important behavior where appropriate, and provide links to the official RabbitMQ docs for further context. The relevant notes for this library can be found here:
https://github.com/cody-greene/node-rabbitmq-client/blob/66c822d644b7d844db8b1adbba1eefd4a0ca4f32/src/Channel.ts#L371-L376

https://github.com/cody-greene/node-rabbitmq-client/blob/66c822d644b7d844db8b1adbba1eefd4a0ca4f32/src/Channel.ts#L437-L442

Also consider using a higher level "Publisher" object for more safety. `rabbit.createPublisher({confirm: true})` https://github.com/cody-greene/node-rabbitmq-client/blob/66c822d644b7d844db8b1adbba1eefd4a0ca4f32/src/Connection.ts#L190-L196
