### ISSUE TITLE
consumer: set requeue on a per message basis

### ISSUE THREAD

**Issue by tttp** [cody-greene/node-rabbitmq-client#20]
Hi,

we're using rabbitmq to call a rest API and we'd like to handle two different types of error:

- short term: if the REST server is busy, it will return a "try later" error, we'd like to requeue the message, pause a bit an retry, possibly closing the Consumer and trying with a lower concurrency
- long term: for whatever reason, the message can't be processed, we would like to nack but not requeue, so the message goes into the dead letter queue, so it gives the option to other messages to be processed

I've seen you can do it when using basicNack, or can set the default when setting up the Consumer. Is there a way to have the both of both world?

bonus if we can do it as well based on the redelivered status of the message

**Comment by cody-greene** [comment]
I could add a "manual ack" mode... but that would likely cause more problems if used incorrectly. A consumer can lock up if your code throws an error before you ack/nack, for example. Perhaps if I made it more passive: a new writable field on the `AsyncMessage` interface?
```typescript
interface AsyncMessage {
  /** Override the default rejection behavior, for this message. */
  requeue?: boolean
}
```

```typescript
rabbit.createConsumer({queue: 'whatever', requeue: false}, async (msg) => {
  // ...
  if (shouldRetry) {
    msg.requeue = true
  }
  // ...
})
```

In the meantime you can probably get away with manually re-publishing the message for your "short term" case.

**Comment by tttp** [comment]
What do you think about using the exception thrown? eg.:

class nackMessage extends Error {
  constructor({requeue?:boolean, message: string}) {
...
  }
}

and if the error thrown isn't of the nackMessage or requeue isn't set, it doesn't overwrite the default rejection behaviour, like today

I thought about republish the message, but the access rules we've set up so far is that the consumer can only read, not write (I'm not sure it's that useful, but probably easier to dead-letter everything short term)

**Comment by cody-greene** [comment]
I definitely don't want to search for a special flag on error objects for two reasons:
- Anyone using this library now has to be careful when throwing an error with a "requeue" property. Perhaps they already use this for some unrelated reason. This will have unintended consequences.
- I don't control the errors thrown from user code. Providing a type definition for this would be awkward.

**Comment by tttp** [comment]
- when I've seen the custom error type pattern, the catch block start with testing the type (if error instanceof nackMessage) {// check for requeue } so if it's another object type using requeue, it shouldn't matter

- for pretty much any callback function, it already provides a type definition of what the function is supposed to return, doing the same optionally for an error thrown doesn't feel that different... but fully admit I might be abusing exception ;)

Anyway, back on the table on your initial idea. I think what I find I bit confusing on the msg.requeue proposal is 
- I expect msg to be a read only immutable param, not something that can be changed from within the function 
- have two different paths, one to trigger the nack (throw exception), the other on params on how to process that exception is surprising

what about on the top of throwing error, the ConsumerHandler could optionally return something? eg 

{ status? :  nack/ack, requeue? : boolean}

I'm wondering if it would help to frame it as a broader concern: the ConsumerHandler would benefit from something more complex than a single binary ack/nack "return": there will be many different reasons to nack, with various level of criticality from a "light" requeue to things like updating the concurrency or prefetch, to a fatal "nack everything pending and close")

I'm not saying that your lib should ever try to treat every possible nuance of errors, but I imagine that allowing more than ack/nack is going to be a demand for other things than requeue.


X+

**Comment by cody-greene** [comment]
I get what you're saying. Using the return value sounds good from my perspective of safety and ease-of-use. I'll need some time to think over the details.

-------- Original Message --------

**Comment by cody-greene** [comment]
Is https://github.com/cody-greene/node-rabbitmq-client/pull/21 an adequte solution?

**Comment by tttp** [comment]
Hi @cody-greene, very neat and great solution!

I'm upgrading and testing now
