### ISSUE TITLE
How to mock connection on tests?

### ISSUE THREAD

**Issue by leopucci** [cody-greene/node-rabbitmq-client#22]
Hey there! Nice job man!
I am trying to use but i am having a problem with mocking up the conection while testing or generating documentation. 
While I generate the documentation the connection is made.. 
I am trying to find a way to mock up the conections during tests. 
I already have a variable that tells me if it is testing or not, i just need the mockup with 
the same functions. Anybody already created something like? 

Thanks bro!

**Comment by cody-greene** [comment]
I suggest you avoid mocking the connection but if you really want to then there are libraries for this. Sinon, for example, provides stubs and spies which you could use to create a fake publisher.

-------- Original Message --------

**Comment by leopucci** [comment]
Thank you man! Could you share your thought about avoiding to mock? how do you test code when you don´t mock? you need to have a server to answer?
I will use the sinon for it I think.. thanks!

**Comment by cody-greene** [comment]
Yes, just run a rabbitmq instance in a docker container or something.

Others have written aritcles more eloquently, discussing the pros and con of mocks. They do have a place in your testing toolkit, but for something like rabbitmq and other "database-like" services I think it's unhelpful, and even harmful. Do you have any SQL in your code? Do you mock the SQL database connection too? How do you know the queries actually work? How much time do you spend maintaining your mock objects?

I have far more confidence in my tests when I'm using a real database instance. And I don't worry about keeping my mock API in sync with the real API either.

**Comment by leopucci** [comment]
I do agree with you, but the company that i work for uses github actions and ci/cd over github that makes the deploys. they don´t have access to the postgres or mongo servers.. or rabbit.. 
locally whe can test with the database but on ci/cd we can´t that´s why the tests are always mocked with sinon even the axios requests, etc
Thanks man for your thoughts, 
Have a nice day!

**Comment by cody-greene** [comment]
https://github.com/cody-greene/node-rabbitmq-client/blob/master/.github/workflows/run-test.yml#L24-L28
