### ISSUE TITLE
how nack in consumer

### ISSUE THREAD

**Issue by primemb** [cody-greene/node-rabbitmq-client#24]
Hi, i want to ask how to nack work on createConsumer in docs you said if you throw an error in handler it automatically return nack but if I throw an error my app crash this is my code : 

```
this._consumer = this.rabbit.createConsumer(
      {
        queue: process.env.SERVICE_NAME as string,
        queueOptions: {
          durable: true,
          arguments: {
            "x-queue-type": "quorum",
            "x-delivery-limit": 3,
          },
        },
        qos: { prefetchCount: 1 },
        exchanges: [
          { exchange: "router", type: "topic", durable: true },
          { exchange: "x-dead-letter-exchange", type: "direct", durable: true },
        ],
        queueBindings: [{ exchange: "router", routingKey: "transcoder" }],
      },
      async (msg) => {
        await this.transcoderConsumer.handleConsume(
          msg,
          this.sendMessage.bind(this)
        );
      }
    );
```
so if i throw an exception on `handleConsume` my app gets crashes. and in general is it not better to use a boolean here? for example if this function returns true ack message and if it return false nack message

**Comment by cody-greene** [comment]
The consumer is emitting an error event. Attach an event listener with `.on("error", cb)`

And regarding your suggestion, yes see PR #21

-------- Original Message --------

**Comment by primemb** [comment]
I think i am not explaining it well on consumer i have function that can throw an error for many reason so if i not place try catch on that the app get crashed and need fully restart and if i place try catch then handler in createConsumer thinks everything is fine and send ack .and about that PR it looks great

**Comment by cody-greene** [comment]
If your consumer handler throws an error, then the message is rejected (BasicNack) and an error event is emitted. Register an event handler to prevent the crash. Most people just log the errors.

-------- Original Message --------

**Comment by primemb** [comment]
thank you so much
