### ISSUE TITLE
set timeout option for RPC request

### ISSUE THREAD

**Issue by primemb** [cody-greene/node-rabbitmq-client#25]
Hi, i want to ask how timeouts work in rpc client  this is my code right now : 

```
this._rpcClient = this.rabbit.createRPCClient({
      confirm: true,
      maxAttempts: 2,
      timeout: 5000,
      exchanges: [{ exchange: "rpc", durable: true, type: "topic" }],
    });
    
    const res = await this._rpcClient?.send(
        {
          exchange: "rpc",
          routingKey: routeKey,
          expiration: "4000",
        },
        message
      );
```
so do i need to set `expiration` in send method? or just set `timeout` in createRPCClient is enough.
what happend for message after it timeouts in rpc client?

**Comment by cody-greene** [comment]
No you don't need to set an expiration when sending the request. If there is no response after `timeout` milliseconds then [the promise is rejected](https://github.com/cody-greene/node-rabbitmq-client/blob/11586316c77f7d9622ff8a207fe427e30588d43b/src/RPCClient.ts#L199)

```
      const timer = setTimeout(() => {
        dfd.reject(new AMQPError('RPC_TIMEOUT', 'RPC response timed out'))
        this._requests.delete(id)
      }, timeout)
```

Any number of things could have happened to the message at this point, but any response after the timeout will be discarded. What could happen to the request message:
- was never routed to any queue
- is still waiting in a queue
- was rejected by the "server" consumer and not requeued
- "server" consumer took a long time to process the request, response arrives too late
