### ISSUE TITLE
Consumer close deadlock

### ISSUE THREAD

**Issue by Samuron** [cody-greene/node-rabbitmq-client#30]
Hello! I believe the latest version is subject to deadlocks in consumer close. I am not yet able to provide concise reproduction, but approximate scenario in my integration tests is following:
1. Create connection, use lazy channel to declare exchange 
2. Create bunch of publisher and consumers
3. Close publisher and consumers - here is the deadlock occur while closing the underlying channel during executing 
[close callback](https://github.com/cody-greene/node-rabbitmq-client/blob/master/src/Connection.ts#L170). The loop inside [_findNode](https://github.com/cody-greene/node-rabbitmq-client/blob/master/src/SortedMap.ts#L184) never exits and the close promise is not resolved.

Changing first step to avoid using lazy channel and creating explicit channel seems to solve the problem

**Comment by cody-greene** [comment]
Thanks, I'll investigate as soon as I can.
