### ISSUE TITLE
[Question]: Single active consumer

### ISSUE THREAD

**Issue by invalidred** [cody-greene/node-rabbitmq-client#31]
RabbitMq supports [single active consumer](https://www.rabbitmq.com/consumers.html#single-active-consumer) which is useful in my scenario where I run all my consumers in a Pod in Kubernetes with N replicas. For consumers where ordering is necessary, I set appropriate headers to ensure only one consumer will be processing messages (with concurrency of 1)  from the queue, while the other consumer will wait for the active consumer to disconnect etc.. This works nicely as for consumers where ordering does not matter, I can increase throughput by increasing replica count.

I was wondering if I were to use this library (and I really LOVE the consumer/publisher abstractions... the best I've seen so far!), can we set _single active consumer_ option or if that's how it works under hood? 

I hope my questions makes sense.

**Comment by cody-greene** [comment]
Yes, according to [the official docs](https://www.rabbitmq.com/consumers.html#single-active-consumer):
> Single active consumer can be enabled when declaring a queue, with the
> x-single-active-consumer argument set to true

So you can do that with:
```javascript
const rabbit = new Connection()

// if you just want to create the queue (imperative)
await rabbit.queueDeclare({
  queue: 'my-queue',
  arguments: {'x-single-active-consumer': true}
})

// or when creating a consumer (declarative)
const sub = rabbit.createConsumer({
  queue: 'my-queue',
  queueOptions: {
    durable: true, // etc...
    arguments: {'x-single-active-consumer': true}
  },
}, (msg) => {
  console.log(msg)
})
```

I simply haven't added type definitions for all the x- extensions, so you may not see this sort of thing in my generated docs. See also [QueueDeclare arguments](https://github.com/cody-greene/node-rabbitmq-client/blob/3b5b05414ec96d730eafbfc4038f25498f3f3e7f/src/codec.ts#L1208):
```
arguments?: {
  ...
  [k: string]: any
},
```

**Comment by invalidred** [comment]
@cody-greene this is fantastic! Thank you so much!
