### ISSUE TITLE
Re-connect on PRECONDITION_FAILED error

### ISSUE THREAD

**Issue by chriskalmar** [cody-greene/node-rabbitmq-client#33]
First of all, I want to thank you so much for building this superb RMQ client. ❤️ 
I've been using it for quite some time now and am pleased with the results.

There is only one situation I couldn't find a solution to.
Every now and then I get this error message:
```
PRECONDITION_FAILED - delivery acknowledgement on channel 2 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more
```

Unfortunately, the client doesn't re-connect like usual and my worker is just stuck, unable to process any further jobs.

My question is, how can I recover from this error?
I found these 2 places in the code base and it seems like handling that error is not yet implemented:
https://github.com/cody-greene/node-rabbitmq-client/blob/master/src/Channel.ts#L297
https://github.com/cody-greene/node-rabbitmq-client/blob/master/src/Channel.ts#L315

This is a simplified version of my client bootstrapping:
```
  const rabbit = new Connection({
    url: rmqUrl,
    retryLow: 1_000,
    retryHigh: 30_000,
  });

  rabbit.on('error', (error) => {
    logger.error('MQ connection error');
  });

  rabbit.on('connection', () => {
    logger.log('MQ connection successfully (re)established');
  });
```

Is there any way I could re-connect manually from the error handler?
Or better yet, what would you recommend?

Thank you in advance 🙏

**Comment by cody-greene** [comment]
Sounds like your worker tasks can be quite long. While I investigate this you may want to increase the timeout: https://www.rabbitmq.com/consumers.html#acknowledgement-timeout

Which you can apparently do by editing `rabbitmq.conf`, creating a queue policy (rmq 3.12+), or when declaring a queue (rmq 3.12+):
```javascript
const sub = rabbit.createConsumer({
  queue: 'my-queue',
  queueOptions: {
    arguments: {'x-consumer-timeout': 3_600_000} // 1 hour
  }
}, ...)
```

Since your queue already exists, you may want to pick from the first two options.

**Comment by cody-greene** [comment]
Also, the consumer will wait for any in-progress work to return/resolve before restarting. You may be seeing the effect of a consumer callback which never ends. Do you have some action which retries forever? Here's an example of a consumer which causes a consumer timeout error, and reconnects once the async message handler ends:

```javascript
import {Connection} from 'rabbitmq-client'

const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))

const rabbit = new Connection(process.env.RABBITMQ_URL)

rabbit.on('error', (err) => {
  console.log('connection error', err)
})

const sub = rabbit.createConsumer({
  queue: 'my-queue',
  queueOptions: {
    exclusive: true,
    // requires v3.12 server, 1 minute minimum
    arguments: {'x-consumer-timeout': 60_000}
  },
}, async (msg) => {
  console.log('got message')
  // timeout is checked in 1 minute intervals
  if (!msg.redelivered)
    await sleep(125_000)
  console.log('ack')
})

sub.on('error', err => {
  console.log('consumer error', err)
})

sub.on('ready', () => {
  console.log('consumer ready')
})

const pub = rabbit.createPublisher()

sub.once('ready', () => {
  pub.send('my-queue', null)
})

process.on('SIGINT', () => {
  sub.close()
  pub.close()
  rabbit.close()
})
```

```
consumer ready
got message
connection error AMQPChannelError: undefined: PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 60000 ms...
ack
consumer error AMQPChannelError: failed to ack/nack message; channel is closed
consumer ready
got message
ack
```
