### ISSUE TITLE
Consumer handler `reply()` `envelope.routingKey` and `envelope.exchange` conflict

### ISSUE THREAD

**Issue by MarwanAlsoltany** [cody-greene/node-rabbitmq-client#42]
## Problem

The behavior of the `reply()` callback passed to the `ConsumerHandler` has changed between `v4.4.0` and `v4.5.0`.
A change was introduced to allow for overriding message envelope properties (`correlationId` to be specific).
Which resulted in message replies being routed wrongfully due to using both the `routingKey` and the `exchange` for routing the message (as with any normal publisher).

## Cause

The code responsible for this issue can be found here [v4.4.0 - v4.5.0 Diff](https://github.com/cody-greene/node-rabbitmq-client/compare/v4.4.0..v4.5.0#diff-c714752c1e9340f77ae4fa13194e39fe36def059f4492532941ff14e8c2e5536L201)

## Diagnoses 

In RabbitMQ, a message can be published to queue either through an `exchange` that is bound to a `queue` using some `routingKey`. Or a message with `routingKey` that matches a `queue` name exactly.

Previously, the `exchange` was set to an empty string (always overwritten explicitly), which made the `routingKey` the only property responsible for routing the message. Starting from v4.5.0, this property assignment was dropped out, which resulted in the following side-effect: 
- If `reply()` function caller specifies an exchange —for some reason—, the routing will be done based on the `exchange` and the `routingKey`, which will require having to do additional configuration to make a new queue-exchange binding in order for RabbitMQ to know where to deliver that message. This defeats the purpose of the `reply()` function, as it is solely used as a shortcut for RPC replies and resetting the exchange when replying make no sense and shouldn't be allowed.

## Fix

Revert the change made in v4.5.0 and add `{ exchange: '' }` again so that the `{ routingKey: req.replyTo }` is the only field used for routing.

If you don't have the time to fix the issue. I am more than happy to make a PR.

---

BTW, thanks for the package, I really enjoy working with it. You nailed the API design.

**Comment by cody-greene** [comment]
While direct reply is the default as a conterpart to the RPC interface, it is conceivable that somebody may want to use a fanout exchange to send a response to multiple interested queues. Or use other exchange types for whatever reason.

For example, here is a weird little worker which broadcasts replies through a fanout exchange:
```javascript
const sub = rabbit.createConsumer({
  queue: 'broadcaster'
}, async (msg, reply) => {
  // ... do something ...
  await reply('hello', {exchange: msg.headers['x-reply-to-exchange']})
})

const pub = rabbit.createPublisher({
  confirm: true,
  exchanges: [{exchange: 'splitter', type: 'fanout'}],
})

await pub.send({
  routingKey: 'broadcaster', 
  replyTo: 'whatever', 
  headers: {'x-reply-to-exchange': 'splitter'}
}, 'hello')
```

I must admit I'm struggling to come up with a practical use for this, but just the same I see no reason to consider this a bug in need of fixing.

**Comment by cody-greene** [comment]
I agree it's better to use a separate publisher. Removing this now would definitely be a breaking change though. I'll add it to my list for 5.0
