### ISSUE TITLE
`await Publisher.send()` hangs when reconnecting

### ISSUE THREAD

**Issue by grosso-enerbrain** [cody-greene/node-rabbitmq-client#45]
This issue is very difficult to reproduce, in fact I am unable to provide a working snippet with the error.

I have deployed a Lambda function in AWS using this library.
Here's a somewhat similar version of the code:
``` javascript
const { Connection } = require("rabbitmq-client");

let rabbitConnection;
let rabbitPublisher;

exports.handler = async (event) => {
  await setup();

  let message = { "this is": "a message" };

  let outputBuffer = Buffer.from(JSON.stringify(message), "utf-8");

  await rabbitPublisher.send(
    { exchange: "my_exc", routingKey: "a.sample.topic" },
    outputBuffer
  );
  console.log("Message published to a.sample.topic");
};

async function setup() {
  if (!rabbitConnection) {
    console.log("Creating RabbitMQ connection");
    rabbitConnection = new Connection({
      connectionName: "a-name",
      url: "http://localhost:15672", // or whatever the default URL is, i'm using a real rabbitMQ broker deployed on aws
      connectionTimeout: 5000,
      acquireTimeout: 5000,
      retryLow: 300,
      retryHigh: 5100,
      noDelay: true,
    });
    rabbitConnection.on("error", (err) => {
      console.log("RabbitMQ connection error", err);
    });
    rabbitConnection.on("connection", () => {
      console.log("Connection successfully (re)established");
    });

    console.log("creating RabbitMQ publisher");
    rabbitPublisher = rabbitConnection.createPublisher({
      confirm: true,
      maxAttempts: 3,
      exchanges: [
        { exchange: "my_exc", type: "topic", durable: true },
      ],
    });
    rabbitPublisher.on("basic.return", (msg) => {
      console.log("RabbitMQ publisher basic return", msg);
    });
    rabbitPublisher.on("retry", (err, envelope, body) => {
      console.log("RabbitMQ publisher error", envelope, body, err);
    });
  }
}

```

Lambdas exist in a "lambda context", meaning aws will execute the top-level code once, then call the handler function whit the event that triggered the execution.
If a second execution is triggered within a certain time (variable and unspecified, ~2-10 minutes depending on many factors), the top level code doesn't get re-run and instead only the handler function gets called with the new event. This is the reason I'm not closing the connection at the end of the handler function: I'm hoping to reuse it during following executions.
Between executions the lambda context freezes, meaning the underlying node.js loop is stopped. 

The problem I'm facing is the following:
- execution A of the lambda function:
  - everything is fine, the connection gets established and the message is correctly sent to my broker
  - after the execution the lambda context freezes
- 60 seconds pass (>2 rabbitMQ heartbeats)
- execution B of the lambda function:
  - the context un-freezes
  - the execution reaches the line where i do `await rabbitPublisher.send(...)` (verified using console.log)
  - `rabbitConnection` realizes the connection has been closed by the broker (due to missed heartbeats)
  - the connection gets re-established
  - the promise returned by `rabbitPublisher.send(...)` never gets resolved and the code hangs waiting on it
  - the lambda function reaches it's time limit and times out

Here is a screenshot of the logs
![image](https://github.com/cody-greene/node-rabbitmq-client/assets/103436192/a541cbdf-5b1c-45d7-a603-405d4c6451e5)

There are a few lines i didn't include in the snippet (like retrieving the secret containing the credentials to access the broker), but those shouldn't be relevant.

As you can see the problem doesn't always show up, and this makes it even more difficult to debug.
I believe that this could be caused by the reconnect mechanism in itself:
I'm not good with js (or ts, for that matter), but what I feel is that when the publisher `await`s the underlying buffer to be consumed, sometimes the node.js loop gives back control to the heartbeat thing, and when it detects that the connection is down it re-establishes the connection itself, the publisher and the queue (hence the buffer, i believe), but I'm still `await`ing on the old buffer's promise which does never get resolved.
This could very well be complete bs, consider it a humble interpretation from a fellow python dev.

Other important details:
- the issue occurs (still, only sometimes) if i forcefully close the connection from the broker web-interface while the lambda context is frozen
- increasing the timeout of the lambda function does not help, it hangs anyway
- the lambda runs on node.js 20
- I'm using rabbitmq-client version 4.5.1
- as a workaround I've configure the lambda to retry once before giving up, but I really don't like it

**Comment by cody-greene** [comment]
Wonderful details, thank you. Unconfirmed messages *should* be rejected when the socket closes, and retry when the connection is reestablished. I'll have to set up some timing tests, see if I can reproduce this. I suspect that using a debugger to "freeze" the application at a breakpoint would be a good simulation of your scenario.

**Comment by cody-greene** [comment]
Hopefully v4.5.2 fixes your issue.

**Comment by grosso-enerbrain** [comment]
It's been 2 full days with no error at all!

Thank you so much for the quick response and fix
