### ISSUE TITLE
Connecting to multiple rabbit servers at the same proceess

### ISSUE THREAD

**Issue by avifatal** [cody-greene/node-rabbitmq-client#54]
Hi
Is there a limitaion / known issue by allowing the same node process to connect to multiple rabbit servers? Any thing in particular that I need to pay attention to?

Thanks

**Comment by cody-greene** [comment]
You can connect to a rabbit cluster with the "hosts" option by supplying the hostname:port for each node.

If you literally mean you just want multiple connections then that should work without issues too.

-------- Original Message --------
