### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by zach-betz-hln** [cody-greene/node-rabbitmq-client#8]
Just wanted to drop by and say thank you for this 🙂 

I've been looking for a RabbitMQ Node.js library that meets these criteria:

- TypeScript support
- Allows specifying multiple nodes in a cluster
- Await-able components
- Good docs and few dependencies

Your library meets all of those 💪. It should be added to this [list](https://www.rabbitmq.com/devtools.html#node-dev) in my humble opinion. 

Cheers 🍹

**Comment by cody-greene** [comment]
Thanks! This means a lot.

-------- Original Message --------

**Comment by zach-betz-hln** [comment]
p.s. Opened a PR on the docs https://github.com/rabbitmq/rabbitmq-website/pull/1605

**Comment by invalidred** [comment]
+1
